project:
  type: website
  output-dir: build
  resources:
    - static/fonts/**
    - CNAME           # ensures custom‑domain file lands in gh‑pages root

website:
  title: "Prof. Dr hab. inż. Radosław Juszczak"
  favicon: /static/img/favicon-32.png
  open-graph: true
  site-url: "/"
  image: /static/img/headshot.jpg
  description: "Prof. Radosław Juszczak's academic website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/index.qmd
        text: Projects
      - href: blog/index.qmd
        text: Blogposts
      - href: publications/index.qmd
        text: Publications
    right:
      - icon: researchgate
        href: https://www.researchgate.net/profile/Radoslaw_Juszczak?ev=hdr_xprf&_sg=9NmP1L-8aEvXvLmpQuNkOldwbD3tB8swqdFZ76PiI8uvm6mbA5Y4leRQnMk9m64u
      - icon: graduation-cap
        href: https://publons.com/researcher/3298853/radoslaw-juszczak/
      - icon: user-graduate
        href: https://scholar.google.com/citations?user=V18nqg0AAAAJ
      - icon: file-alt
        href: https://www.scopus.com/authid/detail.uri?authorId=6603564890
      - icon: envelope-fill
        href: mailto:radoslaw.juszczak@up.poznan.pl

format:
  html:
    theme:
      light: [flatly, styles.scss]
      dark: [darkly, styles-dark.scss]
    toc: true
    page-layout: full
    mainfont: "Barlow"
    monofont: "JetBrains Mono"
